export const ON_VIEWPORT_CHANGE = 'ON_VIEWPORT_CHANGE';

export const USERLOCATIONS_RECEIVE_DATA = 'USERLOCATIONS_RECEIVE_DATA';
export const USERLIST_RECIEVE_DATA = 'USERLIST_RECIEVE_DATA';

export const ON_CLASS_CHANGE = 'ON_CLASS_CHANGE';
