export const ON_VIEWPORT_CHANGE = 'ON_VIEWPORT_CHANGE';

export const USERLOCATIONS_RECEIVE_DATA = 'USERLOCATIONS_RECEIVE_DATA';
export const USERLIST_RECIEVE_DATA = 'USERLIST_RECIEVE_DATA';
export const CLASSLIST_RECIEVE_DATA = 'CLASSLISt_RECIEVE_DATA';

export const ON_CLASS_CHANGE = 'ON_CLASS_CHANGE';
export const ON_VIEWALL_CHANGE = 'ON_VIEWALL_CHANGE';

export const ON_BOTTOM_SLIDER_CHANGE = 'ON_BOTTOM_SLIDER_CHANGE';

export const ON_LIVEORREC_CHANGE = 'ON_LIVEORREC_CHANGE';
